name: Release DNS Manager

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0

      permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build Binary
      run: |
        mkdir -p dist
        go build -o dist/dns-manager

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/dns-manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        